version: '3.8'

services:
  frontend:
    build: ./src/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  backend:
    build: ./src/backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080