apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup
  namespace: monitoring
spec:
  schedule: "0 3 * * *"  # Um 3 Uhr morgens
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: curlimages/curl
            command:
            - /bin/sh
            - -c
            - |
              curl -X GET "http://grafana:3000/api/dashboards" -H "Authorization: Bearer ${GRAFANA_TOKEN}" > /backup/dashboards.json
              aws s3 cp /backup/dashboards.json s3://${BACKUP_BUCKET}/grafana/