apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: url-shortener
data:
  health-check.sh: |
    #!/bin/bash
    
    # Frontend Health Check
    curl -f http://frontend/health || exit 1
    
    # Backend Health Check
    curl -f http://backend/health || exit 1
    
    # Database Health Check
    pg_isready -h $DB_HOST -U $DB_USER || exit 1