name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        cd src/backend
        npm install
        cd ../frontend
        npm install
        
    - name: Run Tests
      run: |
        cd src/backend
        npm test
        cd ../frontend
        npm test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build and push Docker images
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/url-shortener-backend:${{ github.sha }} src/backend
        docker build -t ${{ steps.login-ecr.outputs.registry }}/url-shortener-frontend:${{ github.sha }} src/frontend
        docker push ${{ steps.login-ecr.outputs.registry }}/url-shortener-backend:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/url-shortener-frontend:${{ github.sha }}